#!/bin/bash
set -e

clean() {
	cut -d' ' -f2 | sed -e 's/;$//g' | sort -u
}

in_use() {
	git grep '^\s*use ' | clean
}

provided() {
	git grep '^\s*package ' | clean
}

not_in_repo() {
	comm -23 <(in_use) <(provided)
}

filter_out_system() {
	while read package; do
		perl -e "use $package;" 2>/dev/null || echo $package
	done
}

main() {
	need=$(not_in_repo | filter_out_system)

	set -x
	rm -rf vendor; mkdir vendor;
	./cpanm -l vendor $need
}

main
